/** API Constants for Tezos stats */
export const API_GET_CONTRACT_LOAD = 'API_GET_CONTRACT_LOAD';
export const API_GET_CONTRACT_SUCCESS = 'API_GET_CONTRACT_SUCCESS';
export const API_GET_CONTRACT_ERROR = 'API_GET_CONTRACT_ERROR';

export const API_GET_ENTRY_COINS_LOAD = 'API_GET_ENTRY_COINS_LOAD';
export const API_GET_ENTRY_COINS_SUCCESS = 'API_GET_ENTRY_COINS_SUCCESS';
export const API_GET_ENTRY_COINS_ERROR = 'API_GET_ENTRY_COINS_ERROR';

/** API Constants for Game */
export const API_SET_LOADING_STATE = 'API_SET_LOADING_STATE';
export const API_SET_ENTRY_COINS = 'API_SET_ENTRY_COINS';
export const API_SET_GAME_STARTED = 'API_SET_GAME_STARTED';
export const API_SET_GAME_ITEMS = 'API_SET_GAME_ITEMS';
export const API_ADD_GAME_ITEMS = 'API_ADD_GAME_ITEMS';
export const API_SET_INVENTORY_FULL = 'API_SET_INVENTORY_FULL';